name = "proxy-pool"
main = "src/worker.js"
compatibility_date = "2024-12-06"

[[d1_databases]]
binding = "DB"
database_name = "proxy_pool_d1"
database_id = "aaaaaaaaaaaaaaaaaaaaaa"  # 需要替换为实际的数据库ID

[assets]
directory = "public"

[triggers]
crons = ["0 */4 * * *"]

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true



